name: our growing family
favicon: null
layout_spectrum: 0
typography_spectrum: 0.1934278889093548
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.1875
  lightness: 0.7080728446599096
  saturation: 0.06177489901892841
  rhythmicContrast: 0.7611116389743984
purpose: []
